### ISSUE TITLE
Save model

### ISSUE THREAD

**Issue by eutampieri** [liufuyang/rust-nb#9]
Is it possible to save the trained model for future use?
Also, what happens on subsequent calls to `train()`?

**Comment by liufuyang** [comment]
Hi there, unfortunately I haven't considered this feature. But I guess it might be simple to implement on your own. Since all the data is just in a single map, we just need to serialized that map to a file. 

The subsequent calls to train() basically just keep training the model by adding the new training data into the model.

**Comment by eutampieri** [comment]
Thanks for your reply!
However, I should fork the crate because the model is private, right?

**Comment by eutampieri** [comment]
See #10

**Comment by liufuyang** [comment]
Thanks for help, I merged it :)

**Comment by liufuyang** [comment]
I saw your message on the PR, really cool to use this for a chat bot :D 

Also to help your model get persistent, you can see that there is a trait called `ModelStore`
https://github.com/liufuyang/rust-nb/blob/master/src/lib.rs#L51

And for now we have a `ModelHashMapStore` impl that trait basically provide a memory map only solution
https://github.com/liufuyang/rust-nb/blob/master/src/lib.rs#L605-640

What you can do is that basically make a new impl perhaps call it like `ModelHarddriveKVStore` and use some other local disk KV store such as rocksDB or something simpler, then you can create this new type model by writing a new function and perhaps also provide a `load(path)` method so it can use a db file to start.
https://github.com/liufuyang/rust-nb/blob/master/src/lib.rs#L588-L589

All this was my original plan to further make this all work with a model that is storing data directly to harddrive. But I didn't had time and energy to continue all these work :)

**Comment by eutampieri** [comment]
For now I’m happy with the current state… this way I’m able to serialise the entire thing. Also, I think it’s even more flexible this way

Eugenio Tampieri

**Comment by liufuyang** [comment]
So how do you actually serialise it? I wonder what library you use for it :) Do you work on some public repo or, perhaps I can take a look at the code :) ?

**Comment by eutampieri** [comment]
The code is spread across multiple private gitlab repositories… moreover it’s absolute s*it!
However I’ll post the (uncommented) code that uses your crate

**Comment by eutampieri** [comment]
```rust
use rust_stemmers::{Algorithm, Stemmer};
use rust_nb::{Feature, FeatureType, Model};

pub type LabeledText = (String, String);
pub type PredictionResult = std::collections::HashMap<String, f64>;

pub struct Classifier{
    model: Model<rust_nb::ModelHashMapStore>,
}

impl Classifier {
    fn get_bow(&self, text: &str) -> String {
        let remove = vec![',', '.', ';', ':', '\n', '\r', '!', '?', '>'];
        let stemmer = Stemmer::create(Algorithm::Italian);
        let stemmed_sentence: Vec<String> = unidecode::unidecode(text
            .chars()
            .map(|x| if remove.contains(&x){' '} else {x})
            .filter(|x| !x.is_digit(10))
            .collect::<String>().as_str())
            .to_lowercase()
            .split(" ")
            .map(|x| String::from(stemmer.stem(x)))
            .filter(|x| x!="")
            .collect();
        stemmed_sentence.join(" ")
    }
    pub fn new() -> Self {
        Self{model: Model::new().with_stop_words_file("stopwords-it.txt")}
    }
    pub fn load(filename: &str) -> Self {
        let file = std::fs::read(filename).expect("Cannot load model file");
        Self {
            model: bincode::deserialize(&file).expect("Could not parse model")
        }
    }
    pub fn dump(&self, filename: &str) -> Result<(), std::io::Error> {
        let bytes = bincode::serialize(&self.model)/*?;*/.expect("Cannot serialize model");
        std::fs::write(filename, &bytes)
    }
    pub fn train(&mut self, dataset: &Vec<LabeledText>) {
        let mut train_vec: Vec<(String, Vec<Feature>)> = Vec::new();
        for item in dataset {
            train_vec.push((item.0.clone(), vec![Feature{
                feature_type: FeatureType::Text,
                name: "text".to_owned(),
                value: self.get_bow(&item.1)
            }, Feature{
                feature_type: FeatureType::Gaussian,
                name: "len".to_owned(),
                value: format!("{}", &item.1.len())
            }]));
        }
        self.model.train("cpbot", &train_vec);
    }
    pub fn predict(&self, sentence: &str) -> PredictionResult{
        let feature = vec![Feature{
            feature_type: FeatureType::Text,
            name: "text".to_owned(),
            value: self.get_bow(sentence)
        }, Feature{
            feature_type: FeatureType::Gaussian,
            name: "len".to_owned(),
            value: format!("{}", sentence.len())
        }];
        self.model.predict("cpbot", &feature)
    }
}
```

**Comment by liufuyang** [comment]
Thanks. Nice that you found the `.with_stop_words_file("stopwords-it.txt")` to use 👍 

The code looks solid as well. Hope it can work out for you then 😄

**Comment by eutampieri** [comment]
Feel free to reopen
